### ISSUE TITLE
Problem with trailing zeros when sending

### ISSUE THREAD

**Issue by vx28643** [aspanta/emercoin-basic-ios#1]
Hello. I have been testing the Emercoin Basic iOS app - great work. However, I find an issue with the sending amount.

If I try to send 20 emc, the wallet sends only 2 emc
If I try to send 200 emc, the wallet again sends only 2 emc
However, if I send 20.0 then the wallet sends 20 emc
Also sending e.g. 22 emc works fine...

Therefore I think it is a problem with trailing 0's being cut - please check this.

Also please tell me which is the intended repository for the app? If https://github.com/emercoin/emercoin-basic-ios please consider to open Issues on that repository (currently issues are closed there, but support links on the appstore point to that page).

Thank you.

**Comment by snvakula** [comment]
Hello.

We confirm the bug. It will be fixed ASAP.
Now, you can publish the issue to the Github Issues.
Thank you.

**Comment by vx28643** [comment]
excellent, thank you very much

**Comment by vx28643** [comment]
While I had your attention. I would also suggest inclusion of a help link at the bottom of the main login page of the app, where the user can read further information. Because, some users may not understand what they are supposed to do with the login screen. e.g. help: https://www.emercoin.net/basic
